"""Initial migration

Revision ID: e74608b35696
Revises: 
Create Date: 2025-08-04 20:02:12.038397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74608b35696'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('captured_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('captured_date')
        batch_op.drop_column('asset_number')

    # ### end Alembic commands ###
